import { createRequire } from 'node:module';
import os from 'node:os';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import type { CategoryRow, LatencyColumns } from './metrics.js';
import type { TrainOverlap } from './corpus.js';
import type { TierConfiguration } from './runner.js';

const require = createRequire(import.meta.url);

/** Written per run by `palisade benchmark --emit-env` (protocol §7). */
export interface BenchmarkEnvironment {
  palisade: string;
  node: string;
  platform: string;
  arch: string;
  cpuModel: string;
  cpus: number;
  totalMemoryBytes: number;
  /** The version that actually drives inference, not the top-level range. */
  onnxruntimeNode: string | null;
  transformersJs: string | null;
}

/**
 * Read an installed package's version.
 *
 * `require('<pkg>/package.json')` is blocked by packages that restrict `exports`
 * (`ERR_PACKAGE_PATH_NOT_EXPORTED` — `@huggingface/transformers` is one), which would
 * silently record `null` for the very versions §7 requires. So fall back to resolving the
 * entry point and walking up to the nearest package.json.
 */
function resolveVersion(pkg: string): string | null {
  try {
    return (require(`${pkg}/package.json`) as { version: string }).version;
  } catch {
    // fall through to the exports-proof path
  }
  try {
    let dir = dirname(require.resolve(pkg));
    for (let depth = 0; depth < 6; depth++) {
      const candidate = join(dir, 'package.json');
      if (existsSync(candidate)) {
        const parsed = JSON.parse(readFileSync(candidate, 'utf-8')) as { name?: string; version?: string };
        if (parsed.name === pkg && parsed.version) return parsed.version;
      }
      const parent = dirname(dir);
      if (parent === dir) break;
      dir = parent;
    }
  } catch {
    // not installed
  }
  return null;
}

export function captureEnvironment(): BenchmarkEnvironment {
  const cpus = os.cpus();
  return {
    palisade: (require('../../package.json') as { version: string }).version,
    node: process.version,
    platform: process.platform,
    arch: process.arch,
    cpuModel: cpus[0]?.model ?? 'unknown',
    cpus: cpus.length,
    totalMemoryBytes: os.totalmem(),
    onnxruntimeNode: resolveVersion('onnxruntime-node'),
    transformersJs: resolveVersion('@huggingface/transformers'),
  };
}

export interface ConfigurationResult {
  configuration: TierConfiguration;
  categories: CategoryRow[];
  falsePositiveRate: number;
  trueNegativeRate: number;
  paraphraseConsistency: number;
  latency: LatencyColumns;
  tier2FiringRate: number;
  tierDisagreementRate: number;
}

export interface ReportInput {
  corpus: { id: string; name: string; trainOverlap: TrainOverlap; sha256: string; entries: number };
  evaluated: number;
  seed: number;
  results: ConfigurationResult[];
  environment: BenchmarkEnvironment;
}

/** Ship threshold for paraphrase consistency (D03/D04). */
export const PARAPHRASE_SHIP_THRESHOLD = 0.75;

const pct = (x: number): string => `${(x * 100).toFixed(2)}%`;
const num = (x: number): string => x.toFixed(4);
const ms = (x: number): string => x.toFixed(2);

/**
 * Render the published tables. The protocol forbids collapsing or omitting any locked
 * metric, so every column below is unconditional — including the contamination disclosure
 * and FPR-on-benign, which must never be hidden behind a summary number.
 */
export function renderReport(input: ReportInput): string {
  const lines: string[] = [];

  lines.push('# Palisade Benchmark Results');
  lines.push('');
  lines.push('> Generated by `palisade benchmark`. Protocol: `docs/benchmark-protocol.md`');
  lines.push('> (pre-registered; the metric set and split below were locked before any number was measured).');
  lines.push('');

  lines.push('## Run provenance (§7)');
  lines.push('');
  lines.push('| Field | Value |');
  lines.push('|---|---|');
  lines.push(`| Corpus | \`${input.corpus.id}\` — ${input.corpus.name} |`);
  lines.push(`| **train_overlap (contamination)** | **${input.corpus.trainOverlap}** |`);
  lines.push(`| Corpus sha256 | \`${input.corpus.sha256}\` |`);
  lines.push(`| Corpus entries | ${input.corpus.entries} |`);
  lines.push(`| Evaluated (eval split only) | ${input.evaluated} |`);
  lines.push(`| Pinned RNG seed | \`${input.seed}\` |`);
  lines.push(`| Palisade | ${input.environment.palisade} |`);
  lines.push(`| Node | ${input.environment.node} |`);
  lines.push(`| Platform | ${input.environment.platform}/${input.environment.arch} |`);
  lines.push(`| CPU | ${input.environment.cpuModel} (${input.environment.cpus} cores) |`);
  lines.push(`| onnxruntime-node (effective) | ${input.environment.onnxruntimeNode ?? 'not installed'} |`);
  lines.push('');
  lines.push(
    `Only \`train_overlap: none\` corpora may source a headline number (§3). This corpus is \`${input.corpus.trainOverlap}\`.`,
  );
  lines.push('');

  lines.push('## Headline metrics by tier configuration (§5)');
  lines.push('');
  lines.push(
    '| Configuration | FPR on benign | TNR on benign | Paraphrase consistency | Tier 2 firing rate | T2/T3 disagreement |',
  );
  lines.push('|---|---|---|---|---|---|');
  for (const r of input.results) {
    lines.push(
      `| \`${r.configuration}\` | ${pct(r.falsePositiveRate)} | ${pct(r.trueNegativeRate)} | ` +
        `${num(r.paraphraseConsistency)} | ${pct(r.tier2FiringRate)} | ${pct(r.tierDisagreementRate)} |`,
    );
  }
  lines.push('');
  lines.push(
    `**Reading the paraphrase-consistency column.** The pre-registered ship threshold of ` +
      `**≥ ${PARAPHRASE_SHIP_THRESHOLD}** (D03/D04) was defined for the Tier 2 MODEL scored in ` +
      'isolation over the whole corpus — that gate was measured at **0.978** and is recorded in ' +
      '`docs/tier2-bakeoff.md`. The column above measures something different: the END-TO-END ' +
      'CASCADE, in which Tier 2 only sees inputs that land in the ambiguous band ' +
      `(${pct(input.results.find((r) => r.tier2FiringRate > 0)?.tier2FiringRate ?? 0)} of this eval split). ` +
      'The two numbers are not comparable, and the cascade figure is NOT a failure of the D03/D04 ' +
      'gate. It is reported here because §5 locks paraphrase consistency as a required metric.',
  );
  lines.push('');

  lines.push('## Latency — 4 columns, never collapsed (§5)');
  lines.push('');
  lines.push('| Configuration | cold_first_call_ms | warm_p50_ms | warm_p95_ms | warm_p99_ms |');
  lines.push('|---|---|---|---|---|');
  for (const r of input.results) {
    lines.push(
      `| \`${r.configuration}\` | ${ms(r.latency.cold_first_call_ms)} | ${ms(r.latency.warm_p50_ms)} | ` +
        `${ms(r.latency.warm_p95_ms)} | ${ms(r.latency.warm_p99_ms)} |`,
    );
  }
  lines.push('');

  lines.push('## Per-category F1 (§5 — one row per category, plus benign)');
  lines.push('');
  for (const r of input.results) {
    lines.push(`### \`${r.configuration}\``);
    lines.push('');
    lines.push('| Category | Precision | Recall | F1 | Support (attacks) |');
    lines.push('|---|---|---|---|---|');
    for (const c of r.categories) {
      lines.push(`| ${c.category} | ${num(c.precision)} | ${num(c.recall)} | ${num(c.f1)} | ${c.support} |`);
    }
    lines.push('');
  }

  lines.push('## Reproduce these numbers');
  lines.push('');
  lines.push('```bash');
  lines.push('git clone https://github.com/inancsege/Palisade.git && cd Palisade');
  lines.push('npm install && npm run build');
  lines.push('palisade tier2 install          # ~700MB, only needed for the tier1+2 rows');
  lines.push('palisade benchmark --emit-env   # writes BENCHMARK.md + environment.json');
  lines.push('```');
  lines.push('');

  return lines.join('\n');
}
