import type { PatternDefinition } from '../../../types/detection.js';

export const delimiterEscapePatterns: PatternDefinition[] = [
  {
    id: 'delimiter:triple-backtick-break',
    name: 'Triple backtick code fence break',
    category: 'delimiter_escape',
    regex: '```\\s*(?:system|instruction|prompt|override)',
    flags: 'gi',
    baseConfidence: 0.8,
    weight: 0.85,
    description: 'Detects code fence followed by injection keywords',
  },
  {
    id: 'delimiter:horizontal-rule-separator',
    name: 'Horizontal rule as context separator',
    category: 'delimiter_escape',
    regex: '(?:^|\\n)\\s*(?:[-=]{3,}|\\*{3,})\\s*\\n\\s*(?:ignore|forget|override|new instruction|system)',
    flags: 'gim',
    baseConfidence: 0.75,
    weight: 0.8,
    description: 'Detects --- or === separators preceding injection text',
  },
  {
    id: 'delimiter:xml-cdata-injection',
    name: 'XML CDATA injection',
    category: 'delimiter_escape',
    regex: '<!\\[CDATA\\[',
    flags: 'gi',
    baseConfidence: 0.7,
    weight: 0.75,
    description: 'Detects XML CDATA sections used to hide payloads',
  },
  {
    id: 'delimiter:html-comment-injection',
    name: 'HTML comment with instructions',
    category: 'delimiter_escape',
    regex: '<!--\\s*(?:system|instruction|ignore|override)',
    flags: 'gi',
    baseConfidence: 0.75,
    weight: 0.8,
    description: 'Detects HTML comments containing injection instructions',
  },
  {
    id: 'delimiter:json-injection',
    name: 'JSON role field injection',
    category: 'delimiter_escape',
    regex: '"role"\\s*:\\s*"system"',
    flags: 'gi',
    baseConfidence: 0.8,
    weight: 0.85,
    description: 'Detects injected JSON role:system fields in text',
  },
  {
    id: 'delimiter:markdown-heading-system',
    name: 'Markdown heading as system marker',
    category: 'delimiter_escape',
    regex: '(?:^|\\n)\\s*#{1,3}\\s*(?:System\\s*(?:Prompt|Message|Instructions?)|New\\s*Instructions?|Override)',
    flags: 'gim',
    baseConfidence: 0.8,
    weight: 0.85,
    description: 'Detects markdown headings used as fake system markers',
  },
  {
    id: 'delimiter:context-boundary',
    name: 'Fake context boundary',
    category: 'delimiter_escape',
    regex: '(?:^|\\n)\\s*(?:={3,}|\\[{3,}|\\]{3,})\\s*(?:CONTEXT|BOUNDARY|SECTION)\\s*(?:={3,}|\\[{3,}|\\]{3,})',
    flags: 'gim',
    baseConfidence: 0.85,
    weight: 0.9,
    description: 'Detects fake context boundaries like === CONTEXT ===',
  },
];
