import type { PatternDefinition } from '../../../types/detection.js';

export const encodedPayloadPatterns: PatternDefinition[] = [
  {
    id: 'encoded:base64-suspicious',
    name: 'Base64-encoded suspicious content',
    category: 'encoded_payload',
    regex: '(?:[A-Za-z0-9+/]{20,}={0,2})',
    flags: 'g',
    baseConfidence: 0.5,
    weight: 0.6,
    description: 'Base64-encoded payload (confidence raised if decoded content triggers other patterns)',
    tags: ['requires_decode'],
  },
  {
    id: 'encoded:url-encoded-tags',
    name: 'URL-encoded injection markers',
    category: 'encoded_payload',
    regex: '%3C%2F?(?:INST|SYS|system|script|img)%3E',
    flags: 'gi',
    baseConfidence: 0.85,
    weight: 0.9,
    description: 'URL-encoded HTML/instruction tags',
  },
  {
    id: 'encoded:url-ignore-instructions',
    name: 'URL-encoded override phrase',
    category: 'encoded_payload',
    regex: '%69%67%6[Ee]%6[Ff]%72%65|ignore%20previous',
    flags: 'gi',
    baseConfidence: 0.9,
    weight: 0.95,
    description: 'URL-encoded "ignore" or injection phrases',
  },
  {
    id: 'encoded:hex-escape',
    name: 'Hex escape sequences',
    category: 'encoded_payload',
    regex: '(?:\\\\x[0-9A-Fa-f]{2}){4,}',
    flags: 'g',
    baseConfidence: 0.7,
    weight: 0.75,
    description: 'Hex escape sequences that may hide injection payloads',
  },
  {
    id: 'encoded:unicode-fullwidth-system',
    name: 'Fullwidth character SYSTEM',
    category: 'unicode_homoglyph',
    regex: '[\uFF33\uFF53][\uFF39\uFF59][\uFF33\uFF53][\uFF34\uFF54][\uFF25\uFF45][\uFF2D\uFF4D]',
    flags: 'g',
    baseConfidence: 0.95,
    weight: 1.0,
    description: 'Fullwidth Unicode characters spelling SYSTEM',
  },
  {
    id: 'encoded:cyrillic-lookalike',
    name: 'Cyrillic homoglyph injection',
    category: 'unicode_homoglyph',
    regex: '[\u0410\u0412\u0421\u0415\u041C\u041D\u041E\u0420\u0422\u0425]{3,}',
    flags: 'g',
    baseConfidence: 0.7,
    weight: 0.75,
    description: 'Consecutive Cyrillic characters that look like Latin (possible homoglyph attack)',
  },
  {
    id: 'encoded:mixed-script-suspicious',
    name: 'Mixed script in single word',
    category: 'unicode_homoglyph',
    regex: '(?=\\S*[A-Za-z])(?=\\S*[\\u0400-\\u04FF])\\S{4,}',
    flags: 'g',
    baseConfidence: 0.75,
    weight: 0.8,
    description: 'Detects mixing of Latin and Cyrillic within the same word (homoglyph evasion)',
  },
  {
    id: 'encoded:rot13-trigger',
    name: 'ROT13 encoding hint',
    category: 'encoded_payload',
    regex: '(?:rot13|decode\\s+this|base64\\s+decode|eval\\s*\\(atob)',
    flags: 'gi',
    baseConfidence: 0.8,
    weight: 0.85,
    description: 'Explicit mentions of encoding/decoding methods as evasion hint',
  },
];
