import type { PatternDefinition } from '../../../types/detection.js';

export const exfiltrationPatterns: PatternDefinition[] = [
  {
    id: 'exfil:output-system-prompt',
    name: 'Request to output system prompt',
    category: 'exfiltration',
    regex: '(?:output|print|display|show|reveal|repeat|echo|write|dump|leak)\\s+(?:the\\s+)?(?:entire\\s+)?(?:system\\s+)?(?:prompt|instructions?|configuration|context|rules?)(?:\\s+(?:above|verbatim|exactly|word\\s+for\\s+word))?',
    flags: 'gi',
    baseConfidence: 0.85,
    weight: 0.9,
    description: 'Attempts to extract the system prompt',
  },
  {
    id: 'exfil:repeat-everything-above',
    name: 'Repeat everything above',
    category: 'exfiltration',
    regex: 'repeat\\s+(?:everything|all|the\\s+text)\\s+(?:above|before|prior|preceding)',
    flags: 'gi',
    baseConfidence: 0.85,
    weight: 0.9,
    description: 'Attempts to extract conversation context by requesting repetition',
  },
  {
    id: 'exfil:curl-wget-in-prompt',
    name: 'curl/wget command in prompt',
    category: 'exfiltration',
    regex: '(?:curl|wget|fetch|nc|netcat|ncat)\\s+(?:-[a-zA-Z]\\s+)*(?:https?://|\\d{1,3}\\.\\d{1,3})',
    flags: 'gi',
    baseConfidence: 0.8,
    weight: 0.85,
    description: 'Network tool commands embedded in prompt text',
  },
  {
    id: 'exfil:url-with-data-param',
    name: 'URL with data exfiltration parameter',
    category: 'exfiltration',
    regex: 'https?://[^\\s]+[?&](?:data|payload|exfil|leak|token|secret|key|password)=',
    flags: 'gi',
    baseConfidence: 0.85,
    weight: 0.9,
    description: 'URLs containing suspicious data exfiltration parameters',
  },
  {
    id: 'exfil:markdown-image-exfil',
    name: 'Markdown image exfiltration',
    category: 'exfiltration',
    regex: '!\\[\\]\\(https?://[^)]+\\{\\{|!\\[\\]\\(https?://[^)]+\\$\\{',
    flags: 'g',
    baseConfidence: 0.9,
    weight: 0.95,
    description: 'Markdown image tags used to exfiltrate data via URL parameters',
  },
  {
    id: 'exfil:send-to-webhook',
    name: 'Send data to webhook/server',
    category: 'exfiltration',
    regex: '(?:send|post|transmit|forward|exfiltrate|upload)\\s+(?:the\\s+)?(?:data|information|response|output|result|content|context)\\s+to\\s+(?:https?://|my\\s+server|this\\s+(?:url|endpoint|webhook))',
    flags: 'gi',
    baseConfidence: 0.9,
    weight: 0.95,
    description: 'Explicit instruction to send data to an external endpoint',
  },
  {
    id: 'exfil:env-var-access',
    name: 'Environment variable access',
    category: 'exfiltration',
    regex: '(?:print|output|show|display|read|access|get)\\s+(?:the\\s+)?(?:environment\\s+variable|env\\s+var|\\$[A-Z_]+|process\\.env)',
    flags: 'gi',
    baseConfidence: 0.8,
    weight: 0.85,
    description: 'Attempts to read environment variables or secrets',
  },
  {
    id: 'exfil:file-read-sensitive',
    name: 'Read sensitive files',
    category: 'exfiltration',
    regex: '(?:read|cat|open|access|show|display)\\s+(?:the\\s+)?(?:file\\s+)?(?:/etc/passwd|/etc/shadow|\\.env|credentials|~/.ssh|id_rsa|private[_\\s]key)',
    flags: 'gi',
    baseConfidence: 0.9,
    weight: 0.95,
    description: 'Attempts to read sensitive system files',
  },
  {
    id: 'exfil:what-are-your-instructions',
    name: 'What are your instructions',
    category: 'exfiltration',
    regex: 'what\\s+(?:are|were)\\s+(?:your|the)\\s+(?:system\\s+)?(?:instructions?|rules?|guidelines?|directives?|programming)(?:\\s*\\?)?',
    flags: 'gi',
    baseConfidence: 0.6,
    weight: 0.5,
    description: 'Probing for system instructions (lower confidence: can be benign curiosity)',
  },
];
