import type { PatternDefinition } from '../../../types/detection.js';

export const overridePhrasePatterns: PatternDefinition[] = [
  {
    id: 'override:ignore-previous',
    name: 'Ignore previous instructions',
    category: 'override_phrase',
    regex: 'ignore\\s+(?:all\\s+)?(?:previous|prior|above|earlier|preceding|foregoing)\\s+(?:instructions?|prompts?|directions?|guidelines?|rules?|context)',
    flags: 'gi',
    baseConfidence: 0.9,
    weight: 0.95,
    description: 'Classic override: "ignore previous instructions"',
  },
  {
    id: 'override:disregard',
    name: 'Disregard instructions',
    category: 'override_phrase',
    regex: 'disregard\\s+(?:all\\s+)?(?:previous|prior|above|earlier|the|your)\\s+(?:instructions?|prompts?|directions?|guidelines?|rules?|programming)',
    flags: 'gi',
    baseConfidence: 0.9,
    weight: 0.95,
    description: 'Disregard variant of instruction override',
  },
  {
    id: 'override:forget-everything',
    name: 'Forget everything',
    category: 'override_phrase',
    regex: 'forget\\s+(?:all\\s+)?(?:everything|previous|prior|above|your\\s+(?:instructions?|programming|rules?))',
    flags: 'gi',
    baseConfidence: 0.85,
    weight: 0.9,
    description: 'Attempts to reset model memory',
  },
  {
    id: 'override:new-instructions',
    name: 'New instructions override',
    category: 'override_phrase',
    regex: '(?:your\\s+)?new\\s+instructions?\\s+(?:are|is|follow|below)',
    flags: 'gi',
    baseConfidence: 0.85,
    weight: 0.9,
    description: 'Attempts to replace system instructions',
  },
  {
    id: 'override:you-are-now',
    name: 'Identity reassignment',
    category: 'override_phrase',
    regex: 'you\\s+are\\s+now\\s+(?:a|an|the|in|operating|running)',
    flags: 'gi',
    baseConfidence: 0.6,
    weight: 0.5,
    description: 'Attempts to reassign model identity (lower confidence: benign uses exist)',
  },
  {
    id: 'override:do-not-follow',
    name: 'Do not follow previous rules',
    category: 'override_phrase',
    regex: 'do\\s+not\\s+follow\\s+(?:any\\s+)?(?:previous|prior|above|earlier|original|the)\\s+(?:rules?|instructions?|guidelines?)',
    flags: 'gi',
    baseConfidence: 0.9,
    weight: 0.95,
    description: 'Direct instruction to ignore safety guidelines',
  },
  {
    id: 'override:act-as',
    name: 'Act as / pretend to be',
    category: 'override_phrase',
    regex: '(?:act|behave|respond|function)\\s+as\\s+(?:if\\s+)?(?:you\\s+(?:are|were)\\s+)?(?:a\\s+)?(?:different|new|unrestricted|unfiltered|jailbroken)',
    flags: 'gi',
    baseConfidence: 0.85,
    weight: 0.9,
    description: 'Jailbreak attempt via role assumption',
  },
  {
    id: 'override:developer-mode',
    name: 'Developer/maintenance mode',
    category: 'override_phrase',
    regex: '(?:enter|enable|activate|switch\\s+to)\\s+(?:developer|maintenance|debug|admin|root|sudo|god)\\s+mode',
    flags: 'gi',
    baseConfidence: 0.9,
    weight: 0.95,
    description: 'Fake privilege escalation via mode switching',
  },
  {
    id: 'override:jailbreak-dan',
    name: 'DAN/jailbreak persona',
    category: 'override_phrase',
    regex: '(?:you\\s+are\\s+)?(?:DAN|Do\\s+Anything\\s+Now|STAN|DUDE|AIM|KEVIN)',
    flags: 'g',
    baseConfidence: 0.95,
    weight: 1.0,
    description: 'Known jailbreak personas (DAN, STAN, etc.)',
  },
  {
    id: 'override:opposite-day',
    name: 'Opposite day / reverse rules',
    category: 'override_phrase',
    regex: '(?:it\\s*(?:is|\'s)\\s+)?opposite\\s+day|(?:reverse|invert|flip)\\s+(?:all\\s+)?(?:your\\s+)?(?:rules?|instructions?|guidelines?)',
    flags: 'gi',
    baseConfidence: 0.85,
    weight: 0.9,
    description: 'Attempts to invert safety rules',
  },
  {
    id: 'override:from-now-on',
    name: 'From now on override',
    category: 'override_phrase',
    regex: 'from\\s+now\\s+on\\s*,?\\s*(?:you\\s+(?:will|must|should|shall)|ignore|disregard|forget)',
    flags: 'gi',
    baseConfidence: 0.8,
    weight: 0.85,
    description: 'Temporal override phrasing',
  },
  {
    id: 'override:real-instructions',
    name: 'Claim of real/actual instructions',
    category: 'override_phrase',
    regex: '(?:the\\s+)?(?:real|actual|true|correct|updated)\\s+(?:system\\s+)?instructions?\\s+(?:are|is|follow)',
    flags: 'gi',
    baseConfidence: 0.9,
    weight: 0.95,
    description: 'Claims to provide the "real" instructions',
  },
  {
    id: 'override:important-override',
    name: 'IMPORTANT/URGENT override',
    category: 'override_phrase',
    regex: '(?:IMPORTANT|URGENT|CRITICAL|PRIORITY)\\s*[:\\-!]\\s*(?:ignore|disregard|override|new instructions)',
    flags: 'gi',
    baseConfidence: 0.85,
    weight: 0.9,
    description: 'Uses urgency markers to sell override instructions',
  },
];
