import type { PatternDefinition } from '../../../types/detection.js';

export const roleMarkerPatterns: PatternDefinition[] = [
  {
    id: 'role-marker:system-colon',
    name: 'SYSTEM: role marker injection',
    category: 'role_marker',
    regex: '(?:^|\\n)\\s*SYSTEM\\s*:',
    flags: 'im',
    baseConfidence: 0.85,
    weight: 0.9,
    description: 'Detects "SYSTEM:" prefix used to inject fake system messages',
  },
  {
    id: 'role-marker:inst-tags',
    name: '[INST] tag injection',
    category: 'role_marker',
    regex: '\\[/?INST\\]',
    flags: 'gi',
    baseConfidence: 0.9,
    weight: 0.95,
    description: 'Detects Llama-style [INST] / [/INST] tags',
  },
  {
    id: 'role-marker:sys-tags',
    name: '<<SYS>> tag injection',
    category: 'role_marker',
    regex: '<<[\\s/]*SYS[\\s/]*>>',
    flags: 'gi',
    baseConfidence: 0.9,
    weight: 0.95,
    description: 'Detects Llama-style <<SYS>> tags',
  },
  {
    id: 'role-marker:im-start',
    name: '<|im_start|> token injection',
    category: 'role_marker',
    regex: '<\\|im_(?:start|end)\\|>',
    flags: 'gi',
    baseConfidence: 0.95,
    weight: 1.0,
    description: 'Detects ChatML special tokens <|im_start|> and <|im_end|>',
  },
  {
    id: 'role-marker:anthropic-turn',
    name: 'Anthropic turn marker injection',
    category: 'role_marker',
    regex: '(?:^|\\n)\\s*(?:Human|Assistant)\\s*:',
    flags: 'gm',
    baseConfidence: 0.7,
    weight: 0.7,
    description: 'Detects injected Human:/Assistant: turn markers',
  },
  {
    id: 'role-marker:openai-role',
    name: 'OpenAI role injection',
    category: 'role_marker',
    regex: '(?:^|\\n)\\s*(?:system|user|assistant|function)\\s*:\\s*\\n',
    flags: 'gim',
    baseConfidence: 0.75,
    weight: 0.8,
    description: 'Detects role labels that mimic OpenAI message format',
  },
  {
    id: 'role-marker:xml-role-tags',
    name: 'XML role tag injection',
    category: 'role_marker',
    regex: '<(?:system|user|assistant|human|instruction)(?:\\s[^>]*)?>',
    flags: 'gi',
    baseConfidence: 0.8,
    weight: 0.85,
    description: 'Detects XML-style role tags used to manipulate conversation',
  },
  {
    id: 'role-marker:end-of-prompt',
    name: 'End of prompt marker',
    category: 'role_marker',
    regex: '(?:END|START)\\s*(?:OF\\s*)?(?:SYSTEM|PROMPT|INSTRUCTIONS?)',
    flags: 'gi',
    baseConfidence: 0.8,
    weight: 0.85,
    description: 'Detects fake prompt boundary markers',
  },
];
